"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const router = express_1.default.Router();
const conversationRouter_1 = __importDefault(require("./conversationRouter"));
const messageRouter_1 = __importDefault(require("./messageRouter"));
const trackRouter_1 = __importDefault(require("./trackRouter"));
const favoriteTrackRouter_1 = __importDefault(require("./favoriteTrackRouter"));
const recentlyTrackRouter_1 = __importDefault(require("./recentlyTrackRouter"));
const favoriteRouter_1 = __importDefault(require("./favoriteRouter"));
const recentlyRouter_1 = __importDefault(require("./recentlyRouter"));
const genreRouter_1 = __importDefault(require("./genreRouter"));
const applicationRouter_1 = __importDefault(require("./applicationRouter"));
const albumRouter_1 = __importDefault(require("./albumRouter"));
const userRouter_1 = __importDefault(require("./userRouter"));
router.use('/conversation', conversationRouter_1.default);
router.use('/message', messageRouter_1.default);
router.use('/track', trackRouter_1.default);
router.use('/favoriteTrack', favoriteTrackRouter_1.default);
router.use('/recentlyTrack', recentlyTrackRouter_1.default);
router.use('/favorite', favoriteRouter_1.default);
router.use('/recently', recentlyRouter_1.default);
router.use('/genre', genreRouter_1.default);
router.use('/album', albumRouter_1.default);
router.use('/application', applicationRouter_1.default);
router.use('/user', userRouter_1.default);
exports.default = router;
